# Generated by Django 5.2.6 on 2025-10-01 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ViolationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('Tardiness', 'Tardiness'), ('Using Vape/Cigarette', 'Using Vape/Cigarette'), ('Misbehavior', 'Misbehavior'), ('Bullying', 'Bullying - Physical, Verbal/Emotional, Cyberbullying, Sexual, Racism'), ('Gambling', 'Gambling'), ('Haircut', 'Haircut'), ('Not Wearing Proper Uniform/ID', 'Not Wearing Proper Uniform/ID'), ('Cheating', 'Cheating'), ('Cutting Classes', 'Cutting Classes'), ('Absenteeism', 'Absenteeism'), ('Others', 'Others')], max_length=100)),
                ('severity_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('applicable_grades', models.CharField(default='7,8,9,10,11,12', help_text="Comma-separated grade levels (e.g., '7,8,9')", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Counselor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('office', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed'), ('escalated', 'Escalated')], default='pending', max_length=20)),
                ('report_type', models.CharField(choices=[('incident', 'Incident Report'), ('self_report', 'Self Report'), ('teacher_report', 'Teacher Report'), ('counselor_note', 'Counselor Note'), ('peer_report', 'Peer Report')], default='incident', max_length=20)),
                ('custom_violation', models.CharField(blank=True, max_length=200, null=True)),
                ('severity_assessment', models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], max_length=20, null=True)),
                ('incident_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('witnesses', models.TextField(blank=True, null=True)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('parent_notified', models.BooleanField(default=False)),
                ('disciplinary_action', models.TextField(blank=True, null=True)),
                ('subject_involved', models.CharField(blank=True, help_text='Subject/course related to the incident', max_length=100, null=True)),
                ('academic_impact', models.TextField(blank=True, help_text='Impact on academic performance', null=True)),
                ('assigned_counselor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.counselor')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('system_alert', 'System Alert'), ('report_submitted', 'Report Submitted'), ('report_updated', 'Report Updated'), ('reminder', 'Reminder'), ('announcement', 'Announcement'), ('grade_promotion', 'Grade Promotion'), ('strand_change', 'Strand Change')], default='system_alert', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('related_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.report')),
            ],
            options={
                'db_table': 'api_notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CounselorAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('counseling', 'Individual Counseling'), ('group_session', 'Group Session'), ('parent_meeting', 'Parent Meeting'), ('academic_support', 'Academic Support'), ('career_counseling', 'Career Counseling'), ('referral', 'External Referral'), ('suspension', 'Suspension Recommended'), ('warning', 'Verbal Warning'), ('detention', 'Detention'), ('community_service', 'Community Service'), ('follow_up', 'Follow-up Session'), ('peer_mediation', 'Peer Mediation'), ('behavioral_contract', 'Behavioral Contract')], max_length=50)),
                ('description', models.TextField()),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('effectiveness_rating', models.IntegerField(blank=True, help_text='Rate effectiveness 1-5', null=True)),
                ('involves_academic_performance', models.BooleanField(default=False)),
                ('involves_career_guidance', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.counselor')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counselor_actions', to='api.report')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('grade_level', models.CharField(blank=True, choices=[('7', 'Grade 7'), ('8', 'Grade 8'), ('9', 'Grade 9'), ('10', 'Grade 10'), ('11', 'Grade 11'), ('12', 'Grade 12')], max_length=2, null=True)),
                ('strand', models.CharField(blank=True, choices=[('STEM', 'Science, Technology, Engineering, and Mathematics'), ('PBM', 'Pre-Baccalaureate Maritime'), ('ABM', 'Accountancy, Business and Management'), ('HUMSS', 'Humanities and Social Sciences'), ('HOME_ECONOMICS', 'Home Economics'), ('HOME_ECONOMICS_ICT', 'Home Economics/ICT'), ('ICT', 'Information and Communications Technology'), ('EIM_SMAW', 'Electrical Installation and Maintenance - Shielded Metal Arc Welding'), ('SMAW', 'Shielded Metal Arc Welding'), ('HE', 'Home Economics'), ('EIM', 'Electrical Installation and Maintenance')], help_text='Required for Grade 11 and 12 students', max_length=30, null=True)),
                ('section', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('guardian_name', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StrandChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_strand', models.CharField(choices=[('STEM', 'Science, Technology, Engineering, and Mathematics'), ('PBM', 'Pre-Baccalaureate Maritime'), ('ABM', 'Accountancy, Business and Management'), ('HUMSS', 'Humanities and Social Sciences'), ('HOME_ECONOMICS', 'Home Economics'), ('HOME_ECONOMICS_ICT', 'Home Economics/ICT'), ('ICT', 'Information and Communications Technology'), ('EIM_SMAW', 'Electrical Installation and Maintenance - Shielded Metal Arc Welding'), ('SMAW', 'Shielded Metal Arc Welding'), ('HE', 'Home Economics'), ('EIM', 'Electrical Installation and Maintenance')], max_length=30)),
                ('new_strand', models.CharField(choices=[('STEM', 'Science, Technology, Engineering, and Mathematics'), ('PBM', 'Pre-Baccalaureate Maritime'), ('ABM', 'Accountancy, Business and Management'), ('HUMSS', 'Humanities and Social Sciences'), ('HOME_ECONOMICS', 'Home Economics'), ('HOME_ECONOMICS_ICT', 'Home Economics/ICT'), ('ICT', 'Information and Communications Technology'), ('EIM_SMAW', 'Electrical Installation and Maintenance - Shielded Metal Arc Welding'), ('SMAW', 'Shielded Metal Arc Welding'), ('HE', 'Home Economics'), ('EIM', 'Electrical Installation and Maintenance')], max_length=30)),
                ('previous_section', models.CharField(blank=True, max_length=50, null=True)),
                ('new_section', models.CharField(blank=True, max_length=50, null=True)),
                ('change_reason', models.CharField(choices=[('academic_performance', 'Academic Performance'), ('career_interest', 'Change in Career Interest'), ('family_decision', 'Family Decision'), ('counselor_recommendation', 'Counselor Recommendation'), ('administrative', 'Administrative Decision'), ('other', 'Other')], max_length=30)),
                ('reason_details', models.TextField(blank=True, null=True)),
                ('counselor_notes', models.TextField(blank=True, null=True)),
                ('effective_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strand_changes', to='api.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='report',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='api.student'),
        ),
        migrations.CreateModel(
            name='StudentViolationTally',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_violations', models.IntegerField(default=0)),
                ('active_violations', models.IntegerField(default=0)),
                ('resolved_violations', models.IntegerField(default=0)),
                ('low_severity_count', models.IntegerField(default=0)),
                ('medium_severity_count', models.IntegerField(default=0)),
                ('high_severity_count', models.IntegerField(default=0)),
                ('critical_severity_count', models.IntegerField(default=0)),
                ('academic_violations', models.IntegerField(default=0)),
                ('behavioral_violations', models.IntegerField(default=0)),
                ('bullying_violations', models.IntegerField(default=0)),
                ('dress_code_violations', models.IntegerField(default=0)),
                ('attendance_violations', models.IntegerField(default=0)),
                ('substance_violations', models.IntegerField(default=0)),
                ('technology_violations', models.IntegerField(default=0)),
                ('safety_violations', models.IntegerField(default=0)),
                ('respect_violations', models.IntegerField(default=0)),
                ('other_violations', models.IntegerField(default=0)),
                ('current_grade_violations', models.IntegerField(default=0)),
                ('current_strand_violations', models.IntegerField(default=0)),
                ('current_quarter_violations', models.IntegerField(default=0)),
                ('last_violation_date', models.DateTimeField(blank=True, null=True)),
                ('first_violation_date', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='violation_tally', to='api.student')),
            ],
            options={
                'db_table': 'api_studentviolationtally',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('advising_grade', models.CharField(blank=True, choices=[('7', 'Grade 7'), ('8', 'Grade 8'), ('9', 'Grade 9'), ('10', 'Grade 10'), ('11', 'Grade 11'), ('12', 'Grade 12')], max_length=2, null=True)),
                ('advising_strand', models.CharField(blank=True, choices=[('STEM', 'Science, Technology, Engineering, and Mathematics'), ('PBM', 'Pre-Baccalaureate Maritime'), ('ABM', 'Accountancy, Business and Management'), ('HUMSS', 'Humanities and Social Sciences'), ('HOME_ECONOMICS', 'Home Economics'), ('HOME_ECONOMICS_ICT', 'Home Economics/ICT'), ('ICT', 'Information and Communications Technology'), ('EIM_SMAW', 'Electrical Installation and Maintenance - Shielded Metal Arc Welding'), ('SMAW', 'Shielded Metal Arc Welding'), ('HE', 'Home Economics'), ('EIM', 'Electrical Installation and Maintenance')], help_text='Required if advising Grade 11 or 12', max_length=30, null=True)),
                ('advising_section', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ViolationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_count', models.IntegerField(default=1)),
                ('is_repeat_offense', models.BooleanField(default=False)),
                ('previous_violation_date', models.DateTimeField(blank=True, null=True)),
                ('violations_in_current_grade', models.IntegerField(default=1)),
                ('violations_in_strand', models.IntegerField(default=0, help_text='For SHS students - violations within the same strand')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.report')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violation_history', to='api.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentViolationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_date', models.DateTimeField()),
                ('description', models.TextField()),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed'), ('appealed', 'Under Appeal')], default='active', max_length=20)),
                ('counselor_notes', models.TextField(blank=True, null=True)),
                ('academic_quarter', models.CharField(blank=True, help_text='Q1, Q2, Q3, Q4', max_length=10, null=True)),
                ('academic_year', models.CharField(blank=True, help_text='e.g., 2024-2025', max_length=10, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.counselor')),
                ('related_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.report')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violation_records', to='api.student')),
                ('violation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.violationtype')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddField(
            model_name='report',
            name='violation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.violationtype'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(condition=models.Q(('student_id__isnull', False)), fields=('grade_level', 'strand', 'section', 'student_id'), name='unique_student_placement'),
        ),
        migrations.AlterUniqueTogether(
            name='violationhistory',
            unique_together={('student', 'report')},
        ),
    ]
