# Generated by Django 5.2.6 on 2025-10-15 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentviolationtally',
            old_name='academic_violations',
            new_name='absenteeism_violations',
        ),
        migrations.RenameField(
            model_name='studentviolationtally',
            old_name='attendance_violations',
            new_name='cheating_violations',
        ),
        migrations.RenameField(
            model_name='studentviolationtally',
            old_name='behavioral_violations',
            new_name='cutting_classes_violations',
        ),
        migrations.RenameField(
            model_name='studentviolationtally',
            old_name='dress_code_violations',
            new_name='gambling_violations',
        ),
        migrations.RenameField(
            model_name='studentviolationtally',
            old_name='respect_violations',
            new_name='haircut_violations',
        ),
        migrations.RenameField(
            model_name='studentviolationtally',
            old_name='safety_violations',
            new_name='misbehavior_violations',
        ),
        migrations.RenameField(
            model_name='studentviolationtally',
            old_name='substance_violations',
            new_name='not_wearing_uniform_violations',
        ),
        migrations.RenameField(
            model_name='studentviolationtally',
            old_name='technology_violations',
            new_name='tardiness_violations',
        ),
        migrations.AddField(
            model_name='studentviolationtally',
            name='using_vape_cigarette_violations',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='violationtype',
            name='category',
            field=models.CharField(choices=[('Tardiness', 'Tardiness'), ('Using Vape/Cigarette', 'Using Vape/Cigarette'), ('Misbehavior', 'Misbehavior'), ('Bullying', 'Bullying - Physical, Verbal/Emotional, Cyberbullying, Sexual, Racism'), ('Gambling', 'Gambling'), ('Haircut', 'Haircut'), ('Not Wearing Proper Uniform/ID', 'Not Wearing Proper Uniform/ID'), ('Cheating', 'Cheating'), ('Cutting Classes', 'Cutting Classes'), ('Absenteeism', 'Absenteeism'), ('Others', 'Others')], max_length=100),
        ),
    ]
