# Generated by Django 5.2.6 on 2025-10-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_academic_violations_studentviolationtally_absenteeism_violations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentviolationrecord',
            name='action_taken',
            field=models.TextField(blank=True, null=True),
        ),
    ]
