# Generated by Django 5.2.6 on 2025-11-02 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_teacher_options_teacher_approval_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='severity_assessment',
        ),
        migrations.AddField(
            model_name='report',
            name='counseling_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='counseling_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='counseling_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='requires_counseling',
            field=models.BooleanField(default=True, help_text='Can be toggled by counselor for minor cases'),
        ),
        migrations.AddField(
            model_name='report',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='report',
            name='summons_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='summons_sent_to_reporter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='summons_sent_to_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='verification_notes',
            field=models.TextField(blank=True, help_text="Counselor's notes after verification session"),
        ),
        migrations.AddField(
            model_name='report',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('dismissed', 'Not Verified/Dismissed')], default='pending', help_text='Status of case verification through counseling', max_length=20),
        ),
        migrations.AddField(
            model_name='report',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='Counselor who verified the case', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('under_investigation', 'Under Investigation'), ('summons_sent', 'Summons Sent - Awaiting Counseling'), ('verified', 'Verified - Case Confirmed'), ('dismissed', 'Dismissed - Case Not Verified'), ('resolved', 'Resolved'), ('escalated', 'Escalated')], default='pending', max_length=30),
        ),
        migrations.CreateModel(
            name='CounselingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateTimeField()),
                ('actual_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'Student No Show'), ('rescheduled', 'Rescheduled')], default='scheduled', max_length=20)),
                ('student_attended', models.BooleanField(default=False)),
                ('reporter_attended', models.BooleanField(default=False)),
                ('session_notes', models.TextField(blank=True, help_text='Detailed notes from the counseling session')),
                ('case_verified', models.BooleanField(default=False, help_text='True if case is confirmed, False if dismissed')),
                ('summons_sent', models.BooleanField(default=False)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('session_duration_minutes', models.IntegerField(blank=True, null=True)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('next_session_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.counselor')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counseling_sessions', to='api.report')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counseling_as_reporter', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
            options={
                'verbose_name': 'Counseling Session',
                'verbose_name_plural': 'Counseling Sessions',
                'ordering': ['-scheduled_date'],
            },
        ),
    ]
