# Generated by Django 5.2.6 on 2025-11-06 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_report_severity_assessment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='counselor_notes',
            field=models.TextField(blank=True, help_text='Additional notes from counselor about this report', null=True),
        ),
    ]
