# Generated by Django 5.2.6 on 2025-11-06 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_report_counselor_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='counselor_notes',
            field=models.TextField(blank=True, help_text='Notes from counselor about this report', null=True),
        ),
    ]
