# Generated by Django 5.2.6 on 2025-11-11 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_report_counselor_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='school_year',
            field=models.CharField(default='2024-2025', max_length=10),
        ),
        migrations.AlterModelTable(
            name='student',
            table='students',
        ),
    ]
