# Generated by Django 5.2.6 on 2025-11-11 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_student_school_year_alter_student_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentviolationrecord',
            name='school_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='StudentSchoolYearHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year', models.CharField(max_length=20)),
                ('grade_level', models.CharField(max_length=10)),
                ('section', models.CharField(max_length=50)),
                ('strand', models.CharField(blank=True, max_length=50, null=True)),
                ('date_enrolled', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('adviser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advised_students_history', to='api.teacher')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_year_history', to='api.student')),
            ],
            options={
                'db_table': 'student_school_year_history',
                'ordering': ['-school_year', 'grade_level', 'section'],
                'unique_together': {('student', 'school_year')},
            },
        ),
    ]
