# Generated by Django 5.2.6 on 2025-11-12 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_studentviolationrecord_school_year_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentviolationrecord',
            name='related_report',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='related_report',
        ),
        migrations.RemoveField(
            model_name='counseloraction',
            name='report',
        ),
        migrations.RemoveField(
            model_name='counselingsession',
            name='report',
        ),
        migrations.AlterUniqueTogether(
            name='violationhistory',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='counselingsession',
            name='reporter',
        ),
        migrations.RemoveField(
            model_name='counselingsession',
            name='student',
        ),
        migrations.RemoveField(
            model_name='counselingsession',
            name='student_attended',
        ),
        migrations.AddField(
            model_name='counselingsession',
            name='reported_attended',
            field=models.BooleanField(default=False, help_text='Did the reported student attend?'),
        ),
        migrations.AddField(
            model_name='counselingsession',
            name='reported_student',
            field=models.ForeignKey(blank=True, help_text='Student being counseled/reported', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counseling_as_reported', to='api.student'),
        ),
        migrations.AddField(
            model_name='counselingsession',
            name='reporter_student',
            field=models.ForeignKey(blank=True, help_text='Student who reported (if student report)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counseling_as_reporter', to='api.student'),
        ),
        migrations.AlterField(
            model_name='counselingsession',
            name='case_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='counselingsession',
            name='reporter_attended',
            field=models.BooleanField(default=False, help_text='Did the reporter student attend?'),
        ),
        migrations.AlterField(
            model_name='counselingsession',
            name='session_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='counseloraction',
            name='effectiveness_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('system_alert', 'System Alert'), ('report_submitted', 'Report Submitted'), ('report_updated', 'Report Updated'), ('summons', 'Counseling Summons'), ('reminder', 'Reminder'), ('announcement', 'Announcement')], default='system_alert', max_length=20),
        ),
        migrations.AlterField(
            model_name='violationhistory',
            name='violations_in_strand',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='counseloraction',
            table='counselor_actions',
        ),
        migrations.AlterModelTable(
            name='violationhistory',
            table='violation_history',
        ),
        migrations.CreateModel(
            name='StudentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('under_investigation', 'Under Investigation'), ('summons_sent', 'Summons Sent - Awaiting Counseling'), ('verified', 'Verified - Case Confirmed'), ('dismissed', 'Dismissed - Case Not Verified'), ('resolved', 'Resolved'), ('escalated', 'Escalated')], default='pending', max_length=30)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('dismissed', 'Not Verified/Dismissed')], default='pending', help_text='Status of case verification through counseling', max_length=20)),
                ('custom_violation', models.CharField(blank=True, max_length=200, null=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('requires_counseling', models.BooleanField(default=True)),
                ('counseling_date', models.DateTimeField(blank=True, null=True)),
                ('counseling_notes', models.TextField(blank=True)),
                ('counseling_completed', models.BooleanField(default=False)),
                ('summons_sent_at', models.DateTimeField(blank=True, null=True)),
                ('summons_sent_to_reporter', models.BooleanField(default=False, help_text='Summons sent to the student who reported')),
                ('summons_sent_to_reported', models.BooleanField(default=False, help_text='Summons sent to the student being reported')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True)),
                ('counselor_notes', models.TextField(blank=True, null=True)),
                ('incident_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('school_year', models.CharField(blank=True, help_text='School year when report was submitted (e.g., 2024-2025)', max_length=20, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('witnesses', models.TextField(blank=True, null=True)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('parent_notified', models.BooleanField(default=False)),
                ('disciplinary_action', models.TextField(blank=True, null=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_counselor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.counselor')),
                ('reported_student', models.ForeignKey(blank=True, help_text='Student being reported (leave blank if self-reporting)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_reports', to='api.student')),
                ('reporter_student', models.ForeignKey(help_text='Student who submitted this report', on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reports', to='api.student')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_student_reports', to=settings.AUTH_USER_MODEL)),
                ('violation_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.violationtype')),
            ],
            options={
                'db_table': 'student_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='counselingsession',
            name='student_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counseling_sessions', to='api.studentreport'),
        ),
        migrations.AddField(
            model_name='counseloraction',
            name='student_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counselor_actions', to='api.studentreport'),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_student_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.studentreport'),
        ),
        migrations.AddField(
            model_name='studentviolationrecord',
            name='related_student_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='violation_records', to='api.studentreport'),
        ),
        migrations.AddField(
            model_name='violationhistory',
            name='student_report',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.studentreport'),
        ),
        migrations.CreateModel(
            name='TeacherReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('under_investigation', 'Under Investigation'), ('summons_sent', 'Summons Sent - Awaiting Counseling'), ('verified', 'Verified - Case Confirmed'), ('dismissed', 'Dismissed - Case Not Verified'), ('resolved', 'Resolved'), ('escalated', 'Escalated')], default='pending', max_length=30)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('dismissed', 'Not Verified/Dismissed')], default='pending', max_length=20)),
                ('custom_violation', models.CharField(blank=True, max_length=200, null=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('requires_counseling', models.BooleanField(default=True)),
                ('counseling_date', models.DateTimeField(blank=True, null=True)),
                ('counseling_notes', models.TextField(blank=True)),
                ('counseling_completed', models.BooleanField(default=False)),
                ('summons_sent_at', models.DateTimeField(blank=True, null=True)),
                ('summons_sent_to_student', models.BooleanField(default=False, help_text='Summons sent to the reported student')),
                ('teacher_notified', models.BooleanField(default=False, help_text='Teacher notified about counseling session')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True)),
                ('counselor_notes', models.TextField(blank=True, null=True)),
                ('incident_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('school_year', models.CharField(blank=True, help_text='School year when report was submitted', max_length=20, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('witnesses', models.TextField(blank=True, null=True)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('parent_notified', models.BooleanField(default=False)),
                ('disciplinary_action', models.TextField(blank=True, null=True)),
                ('subject_involved', models.CharField(blank=True, help_text='Subject/course where incident occurred', max_length=100, null=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_counselor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.counselor')),
                ('reported_student', models.ForeignKey(help_text='Student being reported by teacher', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_reports', to='api.student')),
                ('reporter_teacher', models.ForeignKey(help_text='Teacher who submitted this report', on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reports', to='api.teacher')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_teacher_reports', to=settings.AUTH_USER_MODEL)),
                ('violation_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.violationtype')),
            ],
            options={
                'db_table': 'teacher_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='counselingsession',
            name='teacher_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counseling_sessions', to='api.teacherreport'),
        ),
        migrations.AddField(
            model_name='counseloraction',
            name='teacher_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counselor_actions', to='api.teacherreport'),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_teacher_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.teacherreport'),
        ),
        migrations.AddField(
            model_name='studentviolationrecord',
            name='related_teacher_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='violation_records', to='api.teacherreport'),
        ),
        migrations.AddField(
            model_name='violationhistory',
            name='teacher_report',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.teacherreport'),
        ),
        migrations.RemoveField(
            model_name='violationhistory',
            name='report',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
