# Generated by Django 5.2.6 on 2025-11-13 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_studentviolationrecord_related_report_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_school_year', models.CharField(default='2024-2025', help_text='Current active school year (e.g., 2024-2025)', max_length=20)),
                ('school_year_start_date', models.DateField(blank=True, help_text='Official start date of current school year', null=True)),
                ('school_year_end_date', models.DateField(blank=True, help_text='Official end date of current school year', null=True)),
                ('is_system_active', models.BooleanField(default=True, help_text='Set to False to freeze system during breaks')),
                ('system_message', models.TextField(blank=True, help_text='Message to display when system is frozen', null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
