# Generated by Django 5.2.6 on 2025-11-19 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
