# Generated by Django 5.2.6 on 2025-11-19 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_student_is_archived_teacher_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentreport',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacherreport',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
