# Generated by Django 5.2.6 on 2025-11-20 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_studentreport_is_archived_teacherreport_is_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedStudent',
            fields=[
            ],
            options={
                'verbose_name': 'Archived Student',
                'verbose_name_plural': 'Archived Students',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.student',),
        ),
        migrations.CreateModel(
            name='ArchivedStudentReport',
            fields=[
            ],
            options={
                'verbose_name': 'Archived Student Report',
                'verbose_name_plural': 'Archived Student Reports',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.studentreport',),
        ),
        migrations.CreateModel(
            name='ArchivedTeacher',
            fields=[
            ],
            options={
                'verbose_name': 'Archived Teacher',
                'verbose_name_plural': 'Archived Teachers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.teacher',),
        ),
        migrations.CreateModel(
            name='ArchivedTeacherReport',
            fields=[
            ],
            options={
                'verbose_name': 'Archived Teacher Report',
                'verbose_name_plural': 'Archived Teacher Reports',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.teacherreport',),
        ),
        migrations.CreateModel(
            name='CounselingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('scheduled_date', models.DateTimeField()),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school_year', models.CharField(max_length=20)),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counseling_logs', to='api.counselor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counseling_logs', to='api.student')),
            ],
            options={
                'db_table': 'counseling_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
