# Generated by Django 5.2.6 on 2025-11-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_archivedstudent_archivedstudentreport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='lrn',
            field=models.CharField(blank=True, help_text='12-digit Learner Reference Number', max_length=12, null=True, unique=True, verbose_name='Learner Reference Number'),
        ),
    ]
