# Generated by Django 5.2.6 on 2025-12-02 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_student_lrn'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('attempt_time', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'login_attempts',
                'ordering': ['-attempt_time'],
                'indexes': [models.Index(fields=['username', '-attempt_time'], name='login_attem_usernam_4a1834_idx'), models.Index(fields=['ip_address', '-attempt_time'], name='login_attem_ip_addr_8008e5_idx')],
            },
        ),
    ]
