# Generated by Django 5.2.6 on 2025-12-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_loginattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='allow_school_year_transition',
            field=models.BooleanField(default=False, help_text='Enable this to allow starting a new school year (archives current data)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='previous_school_year',
            field=models.CharField(blank=True, help_text='Previous school year (for reference)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='transition_date',
            field=models.DateTimeField(blank=True, help_text='Date when school year was transitioned', null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='transition_in_progress',
            field=models.BooleanField(default=False, help_text='School year transition is currently in progress'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='transition_notes',
            field=models.TextField(blank=True, help_text='Notes about the school year transition', null=True),
        ),
    ]
